"""Hugging Face Hub uploader.

Default behavior: take a run directory, package up manifest + best/ + key
logs (events.jsonl, mutations.jsonl) into a Hub model or dataset repo and
upload via `huggingface_hub.HfApi.upload_folder`.

Phase 4 reuses this to publish:
- `Beko2210/algorithm-forge-mutations-vN` — the aggregated mutation dataset
- `Beko2210/algorithm-forge-mutator-qwen-vN` — the fine-tuned mutator model

Auth: standard Hugging Face login (`hf auth login`) or HF_TOKEN env var.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

DEFAULT_USERNAME = "Beko2210"

RepoType = Literal["model", "dataset", "space"]


@dataclass
class UploadResult:
    repo_id: str
    repo_url: str
    files_uploaded: int
    repo_type: RepoType


def _build_readme(run_dir: Path, manifest: dict) -> str:
    cfg = manifest.get("config", {})
    return (
        f"# Algorithm Forge run `{manifest.get('run_id', run_dir.name)}`\n\n"
        f"Generated by [Science Game / Algorithm Forge]"
        f"(https://github.com/BEKO2210/Science_game-).\n\n"
        "## Configuration\n\n"
        f"- **Benchmark**: `{cfg.get('benchmark')}`\n"
        f"- **LLM provider**: `{cfg.get('llm_provider')}` (`{cfg.get('llm_model') or 'default'}`)\n"
        f"- **Generations**: {cfg.get('generations')}\n"
        f"- **Seed**: {cfg.get('seed')}\n"
        f"- **Temperature**: {cfg.get('temperature')}\n\n"
        "## Reproducibility\n\n"
        f"- **Git SHA**: `{manifest.get('git_sha') or 'unknown'}`"
        f"{' (dirty tree)' if manifest.get('git_dirty') else ''}\n"
        f"- **Python**: {manifest.get('python_version')}\n"
        f"- **Platform**: {manifest.get('platform')}\n"
        f"- **Created**: {manifest.get('created_at')}\n\n"
        "## Contents\n\n"
        "- `manifest.json` — full config + environment snapshot\n"
        "- `events.jsonl` — per-generation event log (fitness, timing)\n"
        "- `mutations.jsonl` — parent/child code pairs with fitness delta "
        "(Phase-4 fine-tuning data)\n"
        "- `best/` — best program at each accepted generation\n"
    )


def upload_run(
    run_dir: Path,
    repo_id: str | None = None,
    repo_type: RepoType = "model",
    username: str = DEFAULT_USERNAME,
    private: bool = False,
    token: str | None = None,
) -> UploadResult:
    """Upload a run directory to HF Hub. Creates the repo if it doesn't exist."""
    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError as e:
        raise ImportError(
            "huggingface_hub not installed (should be a base dependency)"
        ) from e

    import json

    run_dir = Path(run_dir)
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"no manifest.json in {run_dir}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    if repo_id is None:
        repo_id = f"{username}/algorithm-forge-{run_dir.name}"

    # Auto-create README before upload.
    readme_path = run_dir / "README.md"
    if not readme_path.exists():
        readme_path.write_text(_build_readme(run_dir, manifest), encoding="utf-8")

    create_repo(
        repo_id=repo_id, repo_type=repo_type, private=private,
        exist_ok=True, token=token,
    )
    api = HfApi(token=token)

    # Upload everything except DVC-style large files & __pycache__.
    api.upload_folder(
        folder_path=str(run_dir),
        repo_id=repo_id,
        repo_type=repo_type,
        ignore_patterns=["__pycache__", "*.pyc", ".launcher.log"],
    )

    files = [p for p in run_dir.rglob("*") if p.is_file()]
    return UploadResult(
        repo_id=repo_id,
        repo_url=f"https://huggingface.co/{'datasets/' if repo_type == 'dataset' else ''}{repo_id}",
        files_uploaded=len(files),
        repo_type=repo_type,
    )
